# Generated by Django 3.0.8 on 2022-07-09 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20220708_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='body',
        ),
    ]
