# Generated by Django 4.2.5 on 2023-09-27 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0005_auto_20220709_1816"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
        migrations.CreateModel(
            name="SentiScore",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_text", models.CharField(max_length=5120)),
                ("senti_score", models.FloatField()),
                ("senti_label", models.CharField(max_length=2560)),
                ("subjectivity_score", models.FloatField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_senti",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
