# Generated by Django 3.0.8 on 2022-07-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('desc', models.CharField(max_length=10240)),
                ('body', models.CharField(max_length=20480)),
                ('img_url', models.URLField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('plat', models.CharField(max_length=16)),
                ('exp', models.CharField(max_length=20480)),
                ('tech', models.CharField(max_length=10240)),
                ('url', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('desc', models.CharField(max_length=20480)),
                ('url', models.URLField(null=True)),
                ('img_url', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('loc', models.CharField(max_length=265)),
                ('duration', models.CharField(max_length=128)),
                ('desc', models.CharField(max_length=20480)),
                ('url', models.URLField(null=True)),
            ],
        ),
    ]
