# Generated by Django 3.0.8 on 2022-07-17 14:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('personalprofile', '0002_blog_course_proj_workexp'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexp',
            name='mt',
            field=models.CharField(default=django.utils.timezone.now, max_length=20480),
            preserve_default=False,
        ),
    ]
