# Generated by Django 3.0.8 on 2022-07-19 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalprofile', '0004_auto_20220718_1734'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.AddField(
            model_name='blog',
            name='blogimg_url',
            field=models.URLField(null=True),
        ),
    ]
